name: efficacy_admin
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # ======================= Styling =======================
  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  flutter_svg: ^2.0.7

  # ======================= Code Generators =======================
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # ======================= Utilities =======================
  intl_phone_number_input: ^0.7.3+1
  expandable: ^5.0.1
  intl_phone_field: ^3.2.0
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_image_compress: ^2.0.4
  image_cropper: ^5.0.0

  # ======================= Authentication =======================
  google_sign_in: ^6.1.5

  # ======================= Storage =======================
  flutter_dotenv: ^5.1.0
  mongo_dart: ^0.9.1
  hive: ^2.2.3
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  cloudinary: ^1.2.0

  # ======================= URL launcher =======================
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ======================= Rules =======================
  flutter_lints: ^2.0.0

  # ======================= Code Generators =======================
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/